version: '3'
services:
    mariadb:
        image: choobs/mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
             - 23308:3306
        volumes:
            - ./data:/var/lib/mysql
            - /etc/localtime:/etc/localtime
            - /etc/timezone:/etc/timezone
